CourseProject/CourseProject/Controllers/DishesController.cs
using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseProject;
using System.IO;
using System.Data.Entity.Infrastructure;

namespace CourseProject.Controllers
{
    public class DishesController : Controller
    {
        private DinnersDBEntities db = new DinnersDBEntities();

        // GET: Dishes
        public ActionResult Index()
        {
            var dishes = db.Dishes.Include(d => d.DishesType);
            return View(dishes.ToList());
        }

        // GET: Dishes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dishes = db.Dishes.Find(id);
            List<string> positions = new List<string>();
            List<string> ingredients = new List<string>();
            foreach (var pos in db.PositionsInDishes.Where(p => p.DishID == id).ToList())
            {
                positions.Add(db.Positions.Where(p => p.ID == pos.PositionID).First().Name);
                int ingrID = db.IngredientsOnPositions.Where(p => p.PositionInDishID == pos.ID).First().IngredientID;
                ingredients.Add(db.Ingredients.Where(i => i.ID == ingrID).First().Name);
            }

            ViewData["Position"] = new SelectList(positions);
            ViewData["Ingredient"] = new SelectList(ingredients);

            if (dishes == null)
            {
                return HttpNotFound();
            }
            return View(dishes);
        }

        // GET: Dishes/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.Type = new SelectList(db.DishesTypes, "ID", "Type");
            ViewData["Positions"] = new SelectList(db.Positions, "ID", "Name");
            ViewData["Ingredients"] = new SelectList(db.Ingredients, "ID", "Name");
            return View();
        }

        // POST: Dishes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "ID,Name,Type,Cost")] Dish dishes, HttpPostedFileBase file)
        {
            ViewData["Positions"] = new SelectList(db.Positions, "ID", "Name");
            ViewData["Ingredients"] = new SelectList(db.Ingredients, "ID", "Name");

            if (ModelState.IsValid && file != null && file.ContentLength > 0)
            {
                List<int> pos_list = new List<int>();
                string pos_str = "";
                foreach (var pos in Request.Form["Positions"].ToList())
                {
                    pos_str += pos;
                }
                string[] pos_arr = pos_str.Split(',');
                foreach (var str in pos_arr)
                {
                    pos_list.Add(Convert.ToInt32(str));
                }


                List<int> ingr_list = new List<int>();
                string ingr_str = "";
                foreach (var ingr in Request.Form["Ingredients"].ToList())
                {
                    ingr_str += ingr;
                }
                string[] ingr_arr = ingr_str.Split(',');
                foreach (var str in ingr_arr)
                {
                    ingr_list.Add(Convert.ToInt32(str));
                }

                foreach (var ingr in ingr_list)
                {
                    double? wght = db.Ingredients.Where(i => i.ID == ingr).First().Weight;
                    if (dishes.Weight == null)
                    {
                        dishes.Weight = wght;
                    }
                    else
                    {
                        dishes.Weight += wght;
                    }
                }
                // extract only the fielname
                var fileName = Path.GetFileName(file.FileName);
                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                file.SaveAs(path);
                dishes.ImageName = "/Images/" + fileName;
                db.Dishes.Add(dishes);
                db.SaveChanges();

                for (int i = 0; i < pos_list.Count; i++)
                {
                    PositionsInDish positionsInDish = new PositionsInDish();
                    IngredientsOnPosition ingredientsOnPosition = new IngredientsOnPosition();

                    positionsInDish.DishID = GetID();
                    positionsInDish.PositionID = pos_list[i];
                    db.PositionsInDishes.Add(positionsInDish);
                    db.SaveChanges();

                    ingredientsOnPosition.PositionInDishID = positionsInDish.ID;
                    ingredientsOnPosition.IngredientID = ingr_list[i];
                    db.IngredientsOnPositions.Add(ingredientsOnPosition);
                    db.SaveChanges();

                    //double? wght = db.Ingredients.Find(ingredientsOnPosition.IngredientID).Weight;
                    //dishes.Weight += wght;
                    //db.Entry(dishes).State = EntityState.Modified;
                    //db.SaveChanges();
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Type = new SelectList(db.DishesTypes, "ID", "Type", dishes.Type);
            return View(dishes);
        }

        // GET: Dishes/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dishes = db.Dishes.Find(id);
            List<string> positions = new List<string>();
            List<int> ingredients = new List<int>();
            foreach (var pos in db.PositionsInDishes.Where(p => p.DishID == id).ToList())
            {
                positions.Add(db.Positions.Where(p => p.ID == pos.PositionID).First().Name);
                int ingrID = db.IngredientsOnPositions.Where(p => p.PositionInDishID == pos.ID).First().IngredientID;
                ingredients.Add(ingrID);
            }
            ViewData["Position"] = new SelectList(positions);
            ViewData["Ingredient"] = new SelectList(ingredients);
            ViewData["Ingredients"] = new SelectList(db.Ingredients, "ID", "Name");

            if (dishes == null)
            {
                return HttpNotFound();
            }

            ViewBag.Type = new SelectList(db.DishesTypes, "ID", "Type", dishes.Type);
            return View(dishes);
        }

        // POST: Dishes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "ID,Weight,Name,Type,Cost,ImageName")] Dish dishes, HttpPostedFileBase file)
        {
            List<int> ingr_list = new List<int>();
            string ingr_str = "";
            foreach (var ingr in Request.Form["Ingredients"].ToList())
            {
                ingr_str += ingr;
            }
            string[] ingr_arr = ingr_str.Split(',');
            foreach (var str in ingr_arr)
            {
                ingr_list.Add(Convert.ToInt32(str));
            }
            ingr_list.Remove(ingr_list.Last());

            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string fileName = System.IO.Path.GetFileName(file.FileName);
                    file.SaveAs(Server.MapPath("~/Images/" + fileName));
                    db.Entry(dishes).State = EntityState.Modified;
                    dishes.ImageName = "/Images/" + fileName;
                    db.SaveChanges();
                }
                else
                {
                    db.Entry(dishes).State = EntityState.Modified;
                    db.SaveChanges();
                }

                int counter = 0;
                foreach (var pos_id in db.PositionsInDishes.Where(p => p.DishID == dishes.ID).Select(p => p.ID).ToList())
                {
                    IngredientsOnPosition ingredientsOnPosition = db.IngredientsOnPositions.Where(i => i.PositionInDishID == pos_id).First();
                    ingredientsOnPosition.IngredientID = ingr_list[counter];
                    db.Entry(ingredientsOnPosition).State = EntityState.Modified;
                    db.SaveChanges();
                    counter++;
                }

                return RedirectToAction("Index");
            }
            ViewBag.Type = new SelectList(db.DishesTypes, "ID", "Type", dishes.Type);
            return View(dishes);
        }


        // GET: Dishes/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dishes = db.Dishes.Find(id);
            if (dishes == null)
            {
                return HttpNotFound();
            }
            return View(dishes);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Dish dishes = db.Dishes.Find(id);
            db.Dishes.Remove(dishes);

CourseProject/CourseProject/Views/Dishes/Create.cshtml
@model CourseProject.Dish

@{
    ViewBag.Title = "Добавление блюда";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/MyScript.js"></script>
<h2 class="page_header">Добавление блюда</h2>


@using (Html.BeginForm("Create", "Dishes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Название: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Тип: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Цена: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <input type="file" name="file" style="align-content:center" required />
        </div>
        <div>
            <div class="form-group">
                @Html.Label("Позиция: ", htmlAttributes: new { @class = "control-label col-md-2", id = "pos_lbl" })
                <div class="col-md-10">
                    @Html.DropDownList("Positions", null, htmlAttributes: new { @class = "form-control", id = "pos_list" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Ингредиент: ", htmlAttributes: new { @class = "control-label col-md-2", id = "ingr_lbl" })
                <div class="col-md-10">
                    @Html.DropDownList("Ingredients", null, htmlAttributes: new { @class = "form-control", id = "ingr_list" })
                </div>
            </div>
        </div>
        <input type="button" value="Добавить позицию" class="btn btn-default" onclick="addPosandIngr()" />
        <input type="button" value="Удалить позицию" class="btn btn-default" onclick="delPosandIngr()" />
        <br />
        <br />

        <div id="container_for_add">
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseProject/CourseProject/Views/Dishes/Delete.cshtml
@model CourseProject.Dish

@{
    ViewBag.Title = "Удаление блюда";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Удаление блюда</h2>

<h3>Вы уверены, что хотите удалить это блюдо?</h3>
<div>
    <hr />
    <table class="details_tbl">
        <tr>
            <td>
                <img src="@Model.ImageName" />
            </td>
            <td>
                <dl class="details_style">
                    <dt>
                        @Html.DisplayName("Имя")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt>
                        @Html.DisplayName("Цена")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cost)
                    </dd>

                    <dt>
                        @Html.DisplayName("Тип")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DishesType.Type)
                    </dd>

                </dl>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Да, удалить" class="btn btn-default" />
                        @Html.ActionLink("Нет, вернуться назад", "Index", "Dishes", htmlAttributes: new { @class = "btn btn-default" })
                    </div>
                }
            </td>
        </tr>
    </table>

</div>

CourseProject/CourseProject/Views/Dishes/Details.cshtml
@model CourseProject.Dish

@{
    ViewBag.Title = "Подробнее";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/MyScript.js"></script>

<h2 class="page_header">Подробнее о <span style="color: maroon; text-decoration: underline;">@Html.DisplayFor(model => model.Name)</span></h2>

<div>
    <p>
        @Html.ActionLink("Редактировать", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Назад", "Index")
    </p>
    <hr />
    <table class="details_tbl">
        <tr>
            <td>
                <img src="@Model.ImageName" />
            </td>
            <td>
                <dl class="details_style" id="dtl">
                    <dt>
                        @Html.DisplayName("Название")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayName("Цена")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cost)
                    </dd>

                    <dt>
                        @Html.DisplayName("Тип")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DishesType.Type)
                    </dd>

                    <dt>
                        @Html.DisplayName("Вес")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Weight)
                    </dd>
                </dl>
                <input id="more" type="button" onclick="details('Details')" value="Ещё..." class="btn btn-default" />
            </td>
        </tr>
    </table>
</div>
<p hidden="hidden">
    @Html.DropDownList("Position", null, htmlAttributes: new { @class = "form-control", id = "pos_list" })
    @Html.DropDownList("Ingredient", null, htmlAttributes: new { @class = "form-control", id = "ingr_list" })
</p>

CourseProject/CourseProject/Views/Dishes/Edit.cshtml
@model CourseProject.Dish

@{
    ViewBag.Title = "Редактирование блюда";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/MyScript.js"></script>
<h2 class="page_header">Редактирование <span style="color: maroon; text-decoration: underline;">@Html.DisplayFor(model => model.Name)</span></h2>

@using (Html.BeginForm("Edit", "Dishes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <table class="details_tbl">
            <tr>
                <td>
                    <img src="@Model.ImageName" />
                </td>
                <td>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.Weight)
                    <dl class="details_style" id="dtl">
                        <dt>
                            @Html.Label("Название", htmlAttributes: new { @class = "control-label col-md-2" })
                        </dt>
                        <dd>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </dd>

                        <dt>
                            @Html.Label("Тип", htmlAttributes: new { @class = "control-label col-md-2" })
                        </dt>
                        <dd>
                            @Html.DropDownList("Type", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        </dd>

                        <dt>
                            @Html.Label("Цена", htmlAttributes: new { @class = "control-label col-md-2" })
                        </dt>
                        <dd>
                            @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                        </dd>
                        <dt>
                            @Html.Label("Фото", htmlAttributes: new { @class = "control-label col-md-2" })
                        </dt>
                        <dd>
                            <input type="file" name="file" />
                            @Html.HiddenFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
                        </dd>

                    </dl>
                    <input id="more" type="button" onclick="details('Edit')" value="Ещё..." class="btn btn-default" />

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Сохранить изменения" class="btn btn-default" />
                        </div>
                    </div>
                </td>
            </tr>
        </table>
        <p hidden="hidden">
            @Html.DropDownList("Position", null, htmlAttributes: new { @class = "form-control", id = "pos_list" })
            @Html.DropDownList("Ingredient", null, htmlAttributes: new { @class = "form-control", id = "ingr_list" })
            @Html.DropDownList("Ingredients", null, htmlAttributes: new { @class = "form-control", id = "ingrs_list" })
        </p>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку блюд", "Index")
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseProject/CourseProject/Views/Dishes/Index.cshtml
@model IEnumerable<CourseProject.Dish>

@{
    ViewBag.Title = "Список блюд";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Список блюд</h2>
<br />
<table class="my_table">
    <tr class=".my_table .header-line">
        <th>
            @Html.DisplayName("Фото")
        </th>
        <th>
            @Html.DisplayName("Название")
        </th>
        <th>
            @Html.DisplayName("Тип")
        </th>
        <th>
            @Html.DisplayName("Вес")
        </th>
        <th>
            @Html.DisplayName("Цена, р")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td align="center">
                <img src="@item.ImageName" class="dish_img" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DishesType.Type)
            </td>
            <td class="number">
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td class="number">
                @Html.DisplayFor(modelItem => item.Cost)
            </td>

            <td>
                @Html.ActionLink("Просмотреть", "Details", new { id = item.ID }, new { @class = "table_buttons" }) |
                @Html.ActionLink("Редактировать", "Edit", new { id = item.ID }, new { @class = "table_buttons" }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.ID }, new { @class = "table_buttons" } )
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Назад", "Index", "Home")
</div>