CourseProject/CourseProject/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseProject;

namespace CourseProject.Controllers
{
    public class PositionsController : Controller
    {
        private DinnersDBEntities db = new DinnersDBEntities();

        // GET: Positions
        public ActionResult Index()
        {
            return View(db.Positions.ToList());
        }

        // GET: Positions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // GET: Positions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Position position)
        {
            if (ModelState.IsValid)
            {
                db.Positions.Add(position);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(position);
        }

        // GET: Positions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Position position)
        {
            if (ModelState.IsValid)
            {
                db.Entry(position).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(position);
        }

        // GET: Positions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Position position = db.Positions.Find(id);
            db.Positions.Remove(position);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseProject/CourseProject/Views/Positions/Create.cshtml
@model CourseProject.Position

@{
    ViewBag.Title = "Добавление позиции блюда";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Добавление позиции блюда</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Название позиции: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseProject/CourseProject/Views/Positions/Delete.cshtml
@model CourseProject.Position

@{
    ViewBag.Title = "Удаление позиции блюда";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Удаление типа блюда</h2>

<h3>Вы уверены, что хотите удалить этот тип?</h3>
<div>
    <hr />
    <dl class="details_style">
        <dt>
            @Html.DisplayName("Позиция блюда")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Да, удалить" class="btn btn-default" />
            @Html.ActionLink("Нет, вернуться назад", "Index", "Positions", htmlAttributes: new { @class = "btn btn-default" })
        </div>
    }
</div>

CourseProject/CourseProject/Views/Positions/Edit.cshtml
@model CourseProject.Position

@{
    ViewBag.Title = "Изменить позицию блюда";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Изменить позицию блюда <span style="color: maroon; text-decoration: underline;">@Html.DisplayFor(model => model.Name)</span></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.Label("Название позиции: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить изменения" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку позиций", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseProject/CourseProject/Views/Positions/Index.cshtml
@model IEnumerable<CourseProject.Position>

@{
    ViewBag.Title = "Список позиций блюд";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Список позиций блюд</h2>

<table class="my_table">
    <tr class=".my_table .header-line">
        <th>
            @Html.DisplayName("Название позиции")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.ID }, new { @class = "table_buttons" }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.ID }, new { @class = "table_buttons" })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Назад", "Index", "Home")
</div>