CourseProject/CourseProject/Controllers/IngredientsCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseProject;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace CourseProject.Controllers
{
    public class IngredientsCategoriesController : Controller
    {
        private DinnersDBEntities db = new DinnersDBEntities();

        // GET: IngredientsCategories
        public ActionResult Index()
        {
            return View(db.IngredientsCategories.ToList());
        }

        // GET: IngredientsCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngredientsCategory ingredientsCategories = db.IngredientsCategories.Find(id);
            if (ingredientsCategories == null)
            {
                return HttpNotFound();
            }
            return View(ingredientsCategories);
        }

        // GET: IngredientsCategories/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: IngredientsCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "ID,Category_Name")] IngredientsCategory ingredientsCategories)
        {
            if (ModelState.IsValid)
            {
                db.IngredientsCategories.Add(ingredientsCategories);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ingredientsCategories);
        }

        // GET: IngredientsCategories/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngredientsCategory ingredientsCategories = db.IngredientsCategories.Find(id);
            if (ingredientsCategories == null)
            {
                return HttpNotFound();
            }
            return View(ingredientsCategories);
        }

        // POST: IngredientsCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "ID,Category_Name")] IngredientsCategory ingredientsCategories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ingredientsCategories).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ingredientsCategories);
        }

        // GET: IngredientsCategories/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngredientsCategory ingredientsCategories = db.IngredientsCategories.Find(id);
            if (ingredientsCategories == null)
            {
                return HttpNotFound();
            }
            return View(ingredientsCategories);
        }

        // POST: IngredientsCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            IngredientsCategory ingredientsCategories = db.IngredientsCategories.Find(id);
            db.IngredientsCategories.Remove(ingredientsCategories);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseProject/CourseProject/Views/IngredientsCategories/Create.cshtml
@model CourseProject.IngredientsCategory

@{
    ViewBag.Title = "Добавление катеогрии ингредиентов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Добавление катеогрии ингредиентов</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Название категории: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseProject/CourseProject/Views/IngredientsCategories/Delete.cshtml
@model CourseProject.IngredientsCategory

@{
    ViewBag.Title = "Удаление категории ингредиента";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Удаление категории ингредиента</h2>

<h3>Вы уверены, что хотите удалить эту категорию?</h3>
<div>
    <hr />
    <dl class="details_style">
        <dt>
            @Html.DisplayName("Название категории")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Да, удалить" class="btn btn-default" />
            @Html.ActionLink("Нет, вернуться назад", "Index", "IngredientsCategories", htmlAttributes: new { @class = "btn btn-default" })
        </div>
    }
</div>

CourseProject/CourseProject/Views/IngredientsCategories/Edit.cshtml
@model CourseProject.IngredientsCategory

@{
    ViewBag.Title = "Редактирование категории ингредиента";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Редактирование категории ингредиента</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.Label("Название категории:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить изменения" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку категорий", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseProject/CourseProject/Views/IngredientsCategories/Index.cshtml
@model IEnumerable<CourseProject.IngredientsCategory>

@{
    ViewBag.Title = "Список категорий ингредиентов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Список категорий ингредиентов</h2>
<br />
<table class="my_table">
    <tr class=".my_table .header-line">
        <th>
            @Html.DisplayName("Название категории")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Category_Name)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.ID }, new { @class = "table_buttons" }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.ID }, new { @class = "table_buttons" })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Назад", "Index", "Home")
</div>