CourseProject/CourseProject/Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseProject;

namespace CourseProject.Controllers
{
    public class IngredientsController : Controller
    {
        private DinnersDBEntities db = new DinnersDBEntities();

        // GET: Ingredients
        public ActionResult Index()
        {
            var ingredients = db.Ingredients.Include(i => i.IngredientsCategory);
            
            return View(ingredients.ToList());
        }

        // GET: Ingredients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredient ingredients = db.Ingredients.Find(id);
            if (ingredients == null)
            {
                return HttpNotFound();
            }
            return View(ingredients);
        }

        // GET: Ingredients/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.Category = new SelectList(db.IngredientsCategories, "ID", "Category_Name");
            return View();
        }

        // POST: Ingredients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "ID,Name,Category,Weight,Availability")] Ingredient ingredients)
        {
            if (ModelState.IsValid)
            {
                db.Ingredients.Add(ingredients);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Category = new SelectList(db.IngredientsCategories, "ID", "Category_Name", ingredients.Category);
            return View(ingredients);
        }

        // GET: Ingredients/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredient ingredients = db.Ingredients.Find(id);
            if (ingredients == null)
            {
                return HttpNotFound();
            }
            ViewBag.Category = new SelectList(db.IngredientsCategories, "ID", "Category_Name", ingredients.Category);
            return View(ingredients);
        }

        // POST: Ingredients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "ID,Name,Category,Weight,Availability")] Ingredient ingredients)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ingredients).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category = new SelectList(db.IngredientsCategories, "ID", "Category_Name", ingredients.Category);
            return View(ingredients);
        }

        // GET: Ingredients/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredient ingredients = db.Ingredients.Find(id);
            if (ingredients == null)
            {
                return HttpNotFound();
            }
            return View(ingredients);
        }

        // POST: Ingredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Ingredient ingredients = db.Ingredients.Find(id);
            db.Ingredients.Remove(ingredients);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseProject/CourseProject/Views/Ingredients/Create.cshtml
@model CourseProject.Ingredient

@{
    ViewBag.Title = "Добавление ингредиента";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Добавление ингредиента</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Название ингредиента: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Категория: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Вес, г: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Наличие: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Availability)
                    @Html.ValidationMessageFor(model => model.Availability, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseProject/CourseProject/Views/Ingredients/Delete.cshtml
@model CourseProject.Ingredient

@{
    ViewBag.Title = "Удаление ингредиента";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Удаление ингредиента</h2>

<h3>Вы уверены, что хотите удалить этот ингредиент?</h3>
<div>
    <hr />
    <dl class="details_style">
        <dt>
            @Html.DisplayName("Название ингредиента")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayName("Вес")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayName("Наличие")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Availability)
        </dd>

        <dt>
            @Html.DisplayName("Категория")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IngredientsCategory.Category_Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Да, удалить" class="btn btn-default" />
            @Html.ActionLink("Нет, вернуться назад", "Index", "Ingredients", htmlAttributes: new { @class = "btn btn-default" })
        </div>
    }
</div>

CourseProject/CourseProject/Views/Ingredients/Details.cshtml
@model CourseProject.Ingredient

@{
    ViewBag.Title = "Подробнее";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Подробнее о <span style="color: maroon; text-decoration: underline;">@Html.DisplayFor(model => model.Name)</span></h2>

<div>
    <p>
        @Html.ActionLink("Редактировать", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Назад", "Index")
    </p>
    <hr />
    <dl class="details_style">
        <dt>
            @Html.DisplayName("Название")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayName("Вес")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
            @Html.Label(", г")
        </dd>

        <dt>
            @Html.DisplayName("Наличие")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Availability)
        </dd>

        <dt>
            @Html.DisplayName("Категория")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IngredientsCategory.Category_Name)
        </dd>

    </dl>
</div>

CourseProject/CourseProject/Views/Ingredients/Edit.cshtml
@model CourseProject.Ingredient

@{
    ViewBag.Title = "Редактирование ингредиента";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Редактирование <span style="color: maroon; text-decoration: underline;">@Html.DisplayFor(model => model.Name)</span></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.Label("Название ингредиента: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Категория: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Вес, г: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Наличие: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Availability)
                    @Html.ValidationMessageFor(model => model.Availability, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить изменения" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку ингредиентов", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseProject/CourseProject/Views/Ingredients/Index.cshtml
@model IEnumerable<CourseProject.Ingredient>

@{
    ViewBag.Title = "Список ингредиентов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page_header">Список ингредиентов</h2>
<br />
<table class="my_table">
    <tr class=".my_table .header-line">
        <th>
            @Html.DisplayName("Название ингредиента")
        </th>
        <th>
            @Html.DisplayName("Категория")
        </th>
        <th>
            @Html.DisplayName("Вес, г")
        </th>
        <th>
            @Html.DisplayName("Наличие")
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IngredientsCategory.Category_Name)
            </td>
            <td class="number">
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.Availability)
            </td>

            <td>
                @Html.ActionLink("Просмотреть", "Details", new { id = item.ID }, new { @class = "table_buttons" }) |
                @Html.ActionLink("Редактировать", "Edit", new { id = item.ID }, new { @class = "table_buttons" }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.ID }, new { @class = "table_buttons" })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Назад", "Index", "Home")
</div>